from __future__ import annotations

from typing import Protocol


class Permissions(Protocol):
    def has_input_access(self) -> bool: ...
    def ensure_input_access(self) -> None: ...
    def has_screen_recording(self) -> bool: ...
    def ensure_screen_recording(self) -> None: ...


