# OS generic config
PYAUTO_PAUSE_SECONDS = 0.05
PYAUTO_FAILSAFE = True
# Mouse animation defaults
DEFAULT_MOVE_SPEED_PPS = 1200.0
DEFAULT_DRAG_SPEED_PPS = 1000.0
MIN_MOVE_DURATION = 0.30
MAX_MOVE_DURATION = 1.5
