# macOS-specific config
MACOS_ACCESSIBILITY_REQUIRED = True
MACOS_ACCESSIBILITY_PROMPT_ON_MISSING = True
# Overlay
PREMOVE_HIGHLIGHT_ENABLED = True
PREMOVE_HIGHLIGHT_DURATION = 4
PREMOVE_HIGHLIGHT_RADIUS = 36
PREMOVE_HIGHLIGHT_COLOR = (255, 0, 0, 255)
PREMOVE_HIGHLIGHT_STROKE_WIDTH = 8.0
PREMOVE_HIGHLIGHT_FILL_COLOR = (255, 0, 0, 220)
PREMOVE_HIGHLIGHT_DEFAULT_DURATION = 0.20
# Quartz screenshot
USE_QUARTZ_SCREENSHOT = True
# Sound
CLICK_SOUND_ENABLED = True
CLICK_SOUND_PATH = 'os_ai_os_macos/assets/sounds/mouse_click.mp3'
CLICK_SOUND_VOLUME = 0.7
DONE_SOUND_ENABLED = True
DONE_SOUND_PATH = 'os_ai_os_macos/assets/sounds/done.mp3'
DONE_SOUND_VOLUME = 0.9
